### ISSUE TITLE
Constant Crash On Pixel 2

### ISSUE THREAD

**Issue by BlazingOne** [ScerIO/PocketMine-MP-Android#1]
I don't know if this is happening for others, but i let the phar download and every time I click "Start Server" it will crash, any solutions?

**Comment by Frago9876543210** [comment]
pls give more information (os version, build number, etc)

**Comment by BlazingOne** [comment]
OS Version: Android Oreo 8.1.0, Build Number: OPM2.171026.006.G1 Model: Pixel 2 (Non XL) Problem: Starting Server causes instant crash of application

**Comment by Frago9876543210** [comment]
can you provide information from logcat?

**Comment by BlazingOne** [comment]
Dumb Question: How do I access logcat?

**Comment by Frago9876543210** [comment]
https://play.google.com/store/apps/details?id=com.nolanlawson.logcat

**Comment by BlazingOne** [comment]
Ok, I guess I have to  run the app, let it crash and send the log?

**Comment by Frago9876543210** [comment]
Yeah

**Comment by BlazingOne** [comment]
Welp, no log showing up

**Comment by SergeShkurko** [comment]
@BlazingOne you can accept invite to join beta releases (https://play.google.com/apps/testing/io.scer.pocketmine) and check again
