### ISSUE TITLE
No mobs spawn

### ISSUE THREAD

**Issue by Emanuel51248** [ScerIO/PocketMine-MP-Android#106]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by GRASSY-coder** [comment]
Dude use plugin called pure entities

**Comment by MeRainbowPanda** [comment]
do you have mob spawning turned on if so then install a plugin if notthen turn it on
