### ISSUE TITLE
Не работает "аварийный стоп"

### ISSUE THREAD

**Issue by yoraze** [ScerIO/PocketMine-MP-Android#107]
**Describe the bug**
Кнопка, которая быстро выключала сервер при каких-то сбоях НЕ РАБОТАЕТ НА ANDROID 9.

**To Reproduce**
1. Заходим в приложение.
2. Запускаем сервер.
3. Убедившись, что сервер работает - нажимаем квадрат в правом верхнем углу.
4. Видим, что ничего не происходит.

**Expected behavior**
Сервер выключился.

**Smartphone**
 - Device: Huawei какой-то там
 - OS: Android 9
 - Version: С первых по последнюю.

**Comment by Frago9876543210** [comment]
У меня Android 9 и все прекрасно работает

**Comment by yoraze** [comment]
Как бы это печально не звучало, но это не решает мою проблему.

**Comment by SergeShkurko** [comment]
исправлено в 2.2.0
