### ISSUE TITLE
[RakLib] Blocked (IP) x.x.x.x for 300 seconds

### ISSUE THREAD

**Issue by ZyValCraft** [ScerIO/PocketMine-MP-Android#11]
Hello, I am French and I do not speak too much English but with your application to each connection that I try on my server after a few seconds I am kick server and I have this error message ..
Do you have any idea how to fix it?
Thank you for your reply !

[17:00:03] [RakLibServer thread/NOTICE]: Blocked 192.168.1.13 for 300 seconds

**Comment by Newcoolboys** [comment]
You might have a false network or internet when will lead to RakLibServer

**Comment by Frago9876543210** [comment]
https://pmmp.readthedocs.io/en/rtfd/faq/connecting/raklibthreadblocked.html

**Comment by SergeShkurko** [comment]
I think this problem more concerns your network in which PokketTine-Mp works, than in the application

If the problem is still in the application and you can explain why - contact me here, I will reveal the issue
