### ISSUE TITLE
Update to 1.13!

### ISSUE THREAD

**Issue by KingOwnageXV** [ScerIO/PocketMine-MP-Android#116]
I cannot load into the server because its on 1.12 and my game is on 1.13. When will this be fixed?

**Comment by KingOwnageXV** [comment]
How about responding instead of closing

**Comment by KingOwnageXV** [comment]
@Frago9876543210 how about responding instead of closing. We want to know when or if it will come out. You guys don't communicate at all

**Comment by Frago9876543210** [comment]
I don't care. __WE ARE NOT PMMP DEVELOPERS AND THIS REPO/APP JUST ALLOWS RUN POCKETMINE ON PHONE__

**Comment by KingOwnageXV** [comment]
@Frago9876543210 if you don't care that's fine but you've closed EVERY single thread asking about it with ZERO answers you're a fucking dick head and should moderate a different github if you don't give a shit. This app is utterly useless now, fuck your lazy developers.
