### ISSUE TITLE
Что-то с цветами в консоли

### ISSUE THREAD

**Issue by yoraze** [ScerIO/PocketMine-MP-Android#12]
Вместо некоторых цветов в консоли пишет так:
[38;5;83m
[38;5;203m

Пофиксите пожалуйста.

**Comment by yoraze** [comment]
Забыл ещё уточнить, что обнаружил это, написав команду /status в консоли.

**Comment by SergeShkurko** [comment]
Fixed in `2.0.0-beta3`
