### ISSUE TITLE
PocketMine-MP needs to be updated

### ISSUE THREAD

**Issue by poopy69666** [ScerIO/PocketMine-MP-Android#124]
Hello there is a problem with PocketMine-MP recently Minecraft updated minecraft bedrock edition into version 1.14.1 and PocketMine-MP creates lan games for 1.14.0 so im saying can u plz update ur app to support version 1.14.1 on minecraft bedrock edition or else there is no use to ur app anymore.

**Comment by Frago9876543210** [comment]
We are not pockekmine developers, but 1.14 and 1.14.1 should be compatible

**Comment by poopy69666** [comment]
But for me the lan game doesnt show up

Op za 21 dec. 2019 16:20 schreef Frago9876543210 <notifications@github.com>:
