### ISSUE TITLE
Could not find file PocketMine-MP.phar!

### ISSUE THREAD

**Issue by YassinElZouhery** [ScerIO/PocketMine-MP-Android#127]
Describe the bug
When i press start a message comes and says "Could not find file PocketMine-MP.phar!
Expected behavior
??

Smartphone (please complete the following information):

Device: [Huawei y62]
OS: [Android 6.0]

**Comment by SergeShkurko** [comment]
@YassinElZouhery first step - downloading PMMP
![image](https://user-images.githubusercontent.com/18213789/73612782-d625cd00-45ff-11ea-948e-7d068f984cd7.png)
