### ISSUE TITLE
Error: ErrorEvent 

### ISSUE THREAD

**Issue by piyushbest** [ScerIO/PocketMine-MP-Android#129]
**Describe the bug**

**To Reproduce**

**Screenshots**
![Screenshot_20191230-103541](https://user-images.githubusercontent.com/42518831/71569684-db6e9400-2af6-11ea-9b00-eee0afcaef51.png)

**Smartphone (please complete the following information):**
 - Device: [PrimeOS]
 - OS: [primeos]

**Comment by SergeShkurko** [comment]
@piyushbest Processor architecture is x64 or ARM ?

**Comment by piyushbest** [comment]
x84

**Comment by piyushbest** [comment]
X86

**Comment by piyushbest** [comment]
primeos x86

**Comment by SergeShkurko** [comment]
see https://github.com/ScerIO/PocketMine-MP-Android/issues/41
now app support only ARM architecture

**Comment by piyushbest** [comment]
any solution

**Comment by piyushbest** [comment]
solution ??

**Comment by SergeShkurko** [comment]
> solution ??

clone repo and replace file php arm to php x86 
-64 binary
locatinon: https://github.com/ScerIO/PocketMine-MP-Android/tree/master/app/src/main/assets

**Comment by piyushbest** [comment]
thx

**Comment by piyushbest** [comment]
can you pls i m on android os
