### ISSUE TITLE
my friends can't connect

### ISSUE THREAD

**Issue by TheSmas** [ScerIO/PocketMine-MP-Android#131]
**Describe the bug**

**To Reproduce**

**Expected behavior**
A clear and concise description of what you expected to 
Screenshot 
![IMG_20200102_162332_643](https://user-images.githubusercontent.com/59444305/71671647-3d8bfb00-2d7c-11ea-88bb-45f4255a6d67.jpg)

**Smartphone: my friend phone contains 3 GB ram and 64 storage and mine 6GB Ram storage 128 processor snapdragon 675 
 - Device: my friend phone Samsung Galaxy A7 my personal phone Samsung Galaxy A70
 - OS: android 9.0
 - Version 1.14

**Comment by SergeShkurko** [comment]
You must be on the same LAN
