### ISSUE TITLE
I killed my server and now he wont work

### ISSUE THREAD

**Issue by Rayter26** [ScerIO/PocketMine-MP-Android#142]
**Describe the bug**

**To Reproduce**???????

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. samsung a5 2017]
 - OS:?????????
 - Version (android) is 8.0

Ok so yesterday i miss clicked a button and it was the black square button who basicly kills your server. Now im stucked with no server and cant delete this one to create another. I am very mad and even if i uninstall the app amd reinstall it, it still keeps the same problem. Please answer me. And if i cant do anything about it, please tell me if there is another app like yours. Thanks for considering my problem,

-Rayter

**Comment by Rayter26** [comment]
[23:53:47] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[23:53:47] [Server thread/EMERGENCY]: Please upload the "/storage/emulated/0/PocketMine-MP/crashdumps/Wed_Jan_8-23.53.47-UTC_2020.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can. Thats what they said

**Comment by SergeShkurko** [comment]
@Rayter26 in your device storage (or sdcard) created dir "PocketMine-MP". Need to find and remove it, then reinstall server by tap on download button 
![image](https://user-images.githubusercontent.com/18213789/72059371-ef7a7880-32e2-11ea-9017-15d3461f46e7.png)

**Comment by Rayter26** [comment]
OMG THANKS IT WORKED YESSSSS

Le jeu. 9 janv. 2020 5:23 a.m., Serge Shkurko <notifications@github.com> a
écrit :

**Comment by SergeShkurko** [comment]
Cool :)
