### ISSUE TITLE
Enchanting plugin for advanced kit won't work

### ISSUE THREAD

**Issue by REALZulfikar** [ScerIO/PocketMine-MP-Android#144]
I really need help fixing this it stops my server and I can't use the plugin to add enchantments to the kit plugin here's the crashdump ===BEGIN CRASH DUMP===
eNrtPIty27aWv4JVOnvtjijrZctWx5l1beexjRvd2Gnu3KqTgUhIYk0SLEBKVnr773vOAUiCtPxI
4nZ3dm7uwyIIHJz3CyR/b82linn2cSWUDmXSGvfbrSyMRWvc2x8djvb7B71RuxVxnZ0rJVVr/Hsr
26Rwu3UFf8xYuxULrfkCR3/VMvkYCF8GYmeXiZtU+JlmKVc8FplQrMcyyWaC6UyFyaLNZlJGbBGu
RAJg5nkUvQgjhJMuuRrv7e3pTCqAvCfiPOKZCPa6exPpX4vsIkyEdzHZS6N8ESZ6bxIuFpvTHObH
54m/5EmmOwhkTyt/74zD7Zf5ZtusvYzra713uhT+9Vmo+SwSQXHvCm4BlBRxs3j92dvBVhGQ1hoP
gO+Z4j78/Ln1rMv+9J13BqPdMXMFiMIRPGFGTPirtwv4Pesx3CslOcSA7J72lyLII6H2TvQm8Scw
e2fQ7wG4AqHpdAtG0ymhNJ3eiZP3XCanMk4jkYF27sjZr6BPrNp5Or0UCnSX0Oo30TL3dvr7oyGg
4q4qEZ5OS4y9576MIoCPG+sdAjm4C+RgeNAAae54z7PQvzaLh3ct7ncH9yyeKOmDPUlloOzfAaU3
Oty/A4rOuMrM6oPm6sp6dvoHh3cA+PjRlwmYaO5nBc+/51qcgh/QbyQPhGqzLbLIszACaV7wMHkj
FwucZez858HwF/awLZfTh/3HTC8sgggd3UfoUa8pf8NDWnnIdvC2Er/loRI7FoXDo1/Yo51Q7aqy
xiY2u61f/mi3xF/gSP96ZwWEme0+hslKRisRiyQDHALgqZ+1irswsmUfuI2EIlP6hzCFwb+9b7+F
4f6RvWTfsv8i6plRUvaNkSHMGXSdOdlSybVm78QcTRmcxvmNL1L8gTN75cw9vOzbyzSfRaHP5nlC
S1jN6dT3A01ZyTDA1QO7+ne8GBaQ4V84ZzvfZMtQe88XInsndB6BObL/OD5mCYS4XbNi31mB/74x
HGLHrMacC56ARqjxGEBNaMbO7ne4/qCxnnY1MLznoT5PSFw7u3a7UWM6bRk0hAqbu4p3m4g2A68g
DAKHWyBCOiG4vwRMboHm+tZ+50mmNha/oy3QCrLg/rB7x33858s8yXa4UnwD6gfmoUH2O1t3+3na
4mk4bf3SZiWzgL4zoX0Vkp7s7NIIagDPQlh/koYQDoCPz1mX/etfiEzvHmTABAiTHdgpiqatNrsf
kV0Ls/8YmPfj/JPJ4lBMd+1pEz1n38GT0OLARaDDO4AaYQ/379nTJdGEEaQuTOYSsLC7onNh0xbr
3IlPAn4SkIEZMG0nDO6fHQbF3F22BEWdCZFARIhlJqINKxahdt8PB5RfGyaghQwP7iFzu5HniRKL
UIMKO5Tu3Iu22Wp0x1Z/tP74dx757zzy33nk/688st1aiEQoHmHOhL4OEyt3NWA0A1ZXhX1r0On1
OgMcz8MogAIf6vt2K9RgpavWeM4jLSBLUzKToL+Q0h0ewSYh5nDdYH/UHc56+wdzPu8dzUQvOJwP
R3w4FPzQnx/xwWzoD+YCYCt+HYUzXNPp9TtdGMktdm/CJL9hkfR5tJQ6Y8POsNMbHjDwApcXEzZ5
d35+MbliH8DNnuQLNmK93rjfhcySnV5esX63d8Q4V/7yYIjJJNTk49aoM+iM4OqTSAIi0FzCzY9S
F1vCAF3wJFCYuJWJqkbWvZAqPpm8drhYjLRbFeuAb0QLz7OlVBo96a/yVylG+A+FAZEcBwcdpBmu
hUm+WmPMltqtQKSAIq6De1rOIXQ7AzGnvLiCOJ1aJMofmGiDvaCQ315efXj77s0ZDK3FTIcZIo1U
nYOtyXhTp8YZdAna74w6/TpBMhEz+F+Nmu6XU2PBTafCYIC5zrSGzYMEbSsUHG3fWkZUJIIkSNsd
Eosg8lQSeyAobcfwQbJPkiy8THkM/tsh1x2tqyaYUZ1Mvv7E108lRwI2nQLyoYbtwT9AqKvh8iBB
JvDevBI8ypYOSfXxOlHdpr2d5VK+Tny/RtfoK2Rn4UHS4KLRuMQQ9BgSL683H7hy1bMYuUUWeyGT
bDNZTer0mdGfJk8ltx94mMkz+A9EY4NK+eMxBL1V4pyrxCGoGKkTdNhUvkt/Gcj1jz+9Pnt98lm0
uK7qHrpc+NOpRcrkCo+h63uMfe9fnTqElUMPaOD5jfAhM1mdnD6ZbYH25Uv4PweFR3pFBfnDbW9o
Rut07N+ypD/ZCxISj5fISbTmGw3uZO1qmzta9+r9zrBOz2QZRmHKLuFPBBnXUwknJbDaQgUPSBhp
xGg6NclrRd7l1cm7q/eTW8R9kCoK7OSKOHf0AaX7b+5fX5w9FU0G2nTqIFC7eJQ3p4B2uZTpezfR
qA27RA0B4f2GjwDXupmENyI6E6tPf4qXqO0ATt3BbtUHTwi/HiJ2mWUpZO0aQaUIqrPgZIAR3wgF
8SFw7a8abEi04UQSoff3e0dNor2TN5NXJz3Myb5KwgV8MMYSI/f3oywyWPHEF8EPYS3hqg3Xk8lb
2XGU+7x/mIrsXuHamuMewrZmeRW1LkqP8zgoVA1ShcJmmc86voz3Slz3ahSaIPhSNGLgS9EMgb2m
Q/qHSCR5D3/zVIbrgKSgB1gUfx8j0R/O3jlU4NX/ituBjen/HoPyOxGA0BNxGio/xyq0RL95p5n0
N0iBOlt2D/r1Mu3gy4lRdvumvt0VAl5wOlPQ9XTeHW1Wmv0GBVciWwrY9uPXyaNWQlT0OJhAuWku
Hhu7J7kSE6HiWiZSjjXLlL7n93mdtIPhixfdLvtPBrtjG+h1Mg+TMHsyu/loNgAPWGDl/PwCX0Fr
iwZqCQcLgBCrhpO8VuA4g3Ul7TUr06p1w64Ej+GmXsrFMvTTp+JEhQtEPxeve9R3GwNKRPccKBg0
8kyeRoKrN3yxcKNGbdxlw+C2rV6tsfUdPBXNmQEHuRsg4SMSESAB9WsDp8/VAovmid5EeXxxuleH
Z+3idMmzhlnQ0K3ivbfNJD4vKapU8bbV1z3NP8QqlLmenHvFeOsOa0Fkq19PYCsExtTK30egRvVi
2QzVzWTQ7FG9DCEB+HvOVfbpqXRESRn3RlQbEwrVr4dIBu3KMqGIVhcx0/GYcXt4VW94VMMuqYB/
5+B2BGY/SqmCZR7qp6L2V4CaFECnU58Qiggh6ny46D2cJwK2tRrADjyQW5xsssVZrHpPVkUDvADg
kV3D/sXfR7UDUNBgGRk+o+C0BNzhhxpTXF1/v7mpUTOgrgj+xdRw+DXUuahMpw3EHqTvYjOJpEuZ
HWi2CAZeqkSdrg+h+AQj5zc3XJmnJ37Fs831Jkl6dfc0/OxMpNYHtiEFUqoN7qe1gDwFKoPJOVye
nf8U2u2pTr3MNhFoZ8UfQxAkYwVhD6RjlxFP05pVFiNNnvQf1fA/+nLRarPxFxcuFUZ7BQ1IoC+V
eJW7xWk5VK/aes3e3Z+T9Re7V78e1VGl7OIDV+mthIoGmy2GBikveHQdquuvdJwARmdXiid6Tgpy
Gcm1c1nT1Yrwud17OtWE7xrwLZIui/uD5L8RKxGB+la0FyMPuKNP/5y8e/vy5OL83T8/DfsD9vMv
zD4Vwkz7GSwKBmt8MV2Kr3JTFrvHt/1eRnLGo4s8Ew6NzuADZF4uRRRtRuvRU2mrLgBOpwvCIgYs
bjf67iaI3JNudvkePJPSuVrxRGRrqa6fjBaEOZ2uCQHb4PuSasfFbc9CAUrnSohPrtjsQLPGaYjs
e74CywDPf/RUdFYQp1ODw+P17yeehFHETzEZCpNGN33Lzf9FfbyNzefo5ZYOGnU/7z1Jtf3Rel+i
9wTnCHc19O5OEB553IoY33njUcfnZn4toa3G6tl6o5/9PoGkep28VU92el5BnE5LJD7jTAUK0vdp
AKqiGqV4MdpU57psn4iKCyyTTfWdm31N7V0h8XACK4NLfPSZ1+KEO9qso3p/pddxEHm8dC4hDxBz
N60xAw+4mHAWxjqS0VPRcab4QiZ4NPDp4hTyE0Ki+PtYLXudrBoahiO3ZLKlvfxn17aodWGyMhpn
kHpY2+jA0Y0ExUjjDLJxqLOS0SVg9VSU2E1Bo8rdH9GlW6/XHQGYINROdl2edgt1JWG0eeJdDNe1
Dvy3NxMZb1B4+kn4y8nFmVjhgp/Cm/D69J9PRa6PwNM4AODT6czgliFu9mC8wvRzExgH7b0aKOQN
DyClCaiirrnJxo0mfw7/svxtxgOAGswMIsCMJmJflc81oP2Bz8UVb5cQZV/yuCJg4HmJ9NbhJ64C
utIiy8JkoTuGEx6I2SMh6+MeTbDjUFWFdI2PjMpIdLIwg2F8kvWYekXmWctOqiRUulmICVvr2aS8
YqcymYcLhu++TNU0edbv9rtet+f1eqx7MO4ejvtDHI9lFhxP826Xj2aAevgSSNa9breLN80eXipV
dtw76g36OLheAke9CILZsZzPcYQnicwTX3gpHax63F+Gwrzyoo9lQpDQcr3UtGpAe44Jfsxv7Bqg
vms3XQAGsQyEmTKXCgCXY3ZH4G2A1XNxna5Su1EQzuehn0fZ5piwNc+FguhKzh/jcIQFmocqfvxB
QPSKRTWqhQicSfhe0vHZ+YuT92+ucNQK6LdcqI3d1A4pkJUdwZ+dlGuNKnv8Lf0DRoHv9TRfCTtr
FYq1FwAn8Zz1+ACHbmbyxkODslMinixyULtjkSzwGh/oLJ9/7WziCMXOMNYynySeA7VY3qLg6Qn9
mlqCIrCrpdCCFexgXAmWLQWTCWhNtuQZ81GgGb5OFSZ+lAcigB/slsIhrEvgHJNzBNCEqflctJnE
wzqNINlMCX7NNjJXFha+zAJSDech7QACxZejog0C/lGsS3B7gZhzEKlma5n8LWPY3OGKITdjINbn
UBoghvh6jqF7vRQJy9OF4lAiLDrTBHXZABtPE8aefVjSKSK+NabB4TAAYZ+SBh5gS4NM3NwmVOlJ
XSAVfomM+AWWG/qCQTIaRMTBGCEbfS2kNmZ0qI839DLPAkhiPftS25hNW/ZdKj+SWgTTFmF2EkVy
zdC8AJni9QS2Cjn7O2ocziHV8+ytMb2CREsht18zzqzHYHYjwwxuQbFcg5jB7wKriUQoKmAmOHCo
jQFIdccD1GaAmLOBeYmqgASEMzRCBioBXEd0ZxtmZYXzrVmUtx1uPPsANRyoHAiOBwFT9D6VNqii
jwOUOPhn8iEsxDdQkCvAffFbziOUC73cx1Y8ygXbsZuyfncXoZsdwSAFui4P5IpN/DHcpr1/zOMZ
sB3Ult5SwBcTGAYBUNQOTXiv7dstBaU4bamgCMtBPfA9hjajdgKz7gUMrg28iIF3mppLyBsIPjgW
5wmoKE4xwC9Jf4AmUGMlb0JQYXyrBkgi00hK5JC3FqHXczQGnINK32Zh9jdgX6ZoWSDQqZJONhaz
HaABBM76xBYiw7OUjglU0xg4aZ/KkwTFGaADlCkJwQSpDoPswf5mcbhYgrdQXC/brnVbzUSOKJWn
mRk1DEPGxICbpYuECwoHbAIzNBbH8Y1CQHs7BqgjqHMSGA3a1XEUrYqlpaZBjIHAoTbG6k1DjWGi
wcw4GFocZug8YrHgs00GHGeXhtVdYq55fYaWX6HU1iFxnjQKvMLaM4AKJdNE4TwEFMHlAfYJwcJ+
TLGlUXKQVk7muZAgKIl+ALUCNzIdN49QG7MuUgG7k4/PlsDm4P88BZi53Yc/xu+vwx+ysZRQsP65
RMmC0wzcBwZgcKwFQrhrgVWvC/mPQYycwAeyCouf/tsTYEh2QSihx2B+DtEtgejGhHlyFrRbGpSN
RWI0LGeLGx+yEF1RZBzX26vzMbt69fqSvXl98foKnPfkzevzSzY5f8cg5/3h/F2bwSR29RZmnbMP
r96+OWeTd29Pzy8vO00XUONHf//AsmMiVCgp4qMj1kigjy+SFdwonW0PeA+xJiDfQlM8fNjVuFkC
BTko0AkOGrQJ6b1L2YySQWKJETbBaXYzgmyAgOutHLmJSLTHW4whmEjQgs7t2agLtuwAsaXCx3zD
cBbRNXI1a0saQL1EqitSB11Lq97djpKlfGApX3A1A8vw7Ktv4PvJAW3nLpkaomNXMbsKfHfMk5yy
GxcTyPxy0MHddhETmkpYqKEJr/M5vSuPG8SVCXbYW+PzjcJDeiLzKChxCSGIrBNW4a8N4JTQB0IP
MFtP7G4vyFncCpKkOgZCSdtcybgItma1neG5qulKGKmxkrylG2yLStW047LISFFkStLDy4UiB3mc
mvTN5IjM3vDwRiGvM5xkFxDuhGZBAb7FvRZg7HwLgyFoQ+CDHVagZFrnAh1DtgSpLYp0Fp0W7lZh
1S4EaXIEm7V2DDY49U4+YTHlL/PkWhe4n/IUR8M4jyHGQnhVrCg2UJDMlF4Gi4qvaC+WlWQxt3UM
svnUYkQbephm5xB0h6XEzqS51dRp8zmBAr6ZXJiQgWUnupRR5uD5UFaKkjZ8rZVyFUgfkXuAnUkw
DJSUY9HDzBpDYUUdLLP8NPQUO+PkKttFBuJTTAXc+0Hdp4fTxHYZxjZEQGq2lJFJMWc8g3IZU31C
GbImUCEbZMi3mdLK3jWhZSbKZNOEt2eulIpb6FbVJlvSBzG8niNAEh5t7GUFMjYEkNeu8lgqgTGF
DAzlWCxRoo+LYdCi1WGvIBcEXTqm5I6dTt63YS3gMAP7WocBqD3lCsZ7lvA9gj9moyLtrjJyTdxx
5nbYSQCOasmj+R7UqqZMCATosN0KNmXYA0IFcwyxCnsOMLcUOb9Br4YpJo/axmni1h/CBOo1IA28
jyBfhpn0+0kyKfLwqvjEMgMXrSGiIsw8TVLPXjcKnwtrkDr8JEpRY8ZeSBgP0YtsCjJ6ozlO1B0e
9c2i3Q6b2DURVwtawG0VbNWEdpwrvkDqQFxAlk4jSmawtI0BefQDXKEIT6MQOzZUq+Nru0Jn7OLq
PWGqgST6xEqeMewNkJSr7Uzd0SncUJzlHq4aE7ZoAIGY5YtxUcs8Zz2sYWwmh1Ur3S8qVm2KeVFU
srjMKkoPgRm/ZaCdLiXUqKicRQkjiiKVnFvAM840XxVOFLsvRZ8K71X2ju/0gScQPCt8DGBqnskv
UmYqt0CFKF3RKWRolL4k0sdXbmgt8PGCb4CHqCyxXBUVLLp/6zPJb3nFPbOlrrxF0YRy2xVX1G8w
CmA+UWY6NTTXSjvXttT3Qesz4xfsGs+sGbMUEopVGOE2xudZe7a7oNPmyaJMqhNcFjVjR7uYVWtf
bW0RmSrvJMYPklBVSvHJqDiy0vT+KBihOVPtDoLB3xRNYPE7ii3OYiI8EaZWxE/+UG0o8FMrjNqM
FA6WhQaQ0Kn7WItShnzcqCQfLJPxJqqp+WwA7EYfctmCZXc7mlwBpID6LqSIgGyxGP+W2AxIu7GS
9sypoHa8BT2lSxtRw9Vpxbw+o82oG67JJJGfQqGkIa8F1xUzSx2znYci2tGaGukAz2N99owtoGbR
FXuq7kbJoc5tFlljXfOQihpwHJDxG9mkMjXNcuKZuUC3T3OsizjE/SgZ9lJr1ehc0VDHrEgzqXNq
2jljG/Cw+0Qllhk28cKKC19RK/sCQcU2VHcPP8LRGCqtrT6cLlP80IojEDAyzxwllDPx9f2xQaWT
xnHaCSVhnMhkE2OJAPaRYTvP1xXqWPfY+6y6TySQx+KLhYJi0zSWys4dJlL48ZLrJn2EHxjw27O3
+MkFe4hgQwH6hLUweSgHy1nTjpoQrwigsY7TW4bIU3LenlePtzIV5GnuW12CoJcUxxZuOkXj0mUd
ZKgJqonT5WmDe0yXvM3w2I3iVVZmLOB55wKqaBAhOKAE44G5W8QV0zPita6RPa5y4k0O2RmENnJi
ha+wAEny5n6xxy1JG1pdUWdQQpeu2gYkBEofdrB5A0oW/SVuSO0wu6hofXaqDewdd4eCm/eHPOu1
jXSNVThdhqItTAdJHbefsLSD5DCwILA5ZvmhH1RFFVCSFc5LQJCpAyGm2Y8OqCiyjYsrTquqwMaj
kGubwUPSxfEBQHuFOQDgaGU1LoRm7oHeYrdnzH6m4A3hs03tn18QqHmqq4yS7iEEkYGJlAoDW2AX
h0FUOW8LWBTPKUBryiWpMAP5hICrjbYu+mZfwsH8ZHh4hEHBBK9qxzF78ebkatz/btTeP7rptQc3
g3b/u953+E0g42J3MiUEfbrr+LBrPLG5Gu7vmqzH9PvdutZYOIYW4LFtO1HmQX0jkJq/YeaDM7kq
fHKRzKuykU8eB+BApPLpJEYXDPOKUwbQBZPePXtBroa2ovk1IDklCvbLd86IR7lWp+qQSfpOFxM3
4Pi0rYP8a0yXNeX8+KmxEBLVjSmZaR7SC6hAlm6iiLEZQyXBh1xElb661W6Jm0wkmt7qGP/eOoUE
wflKSkDP0JSXoACJ1pEzkvq1+fo3QEcM3O+smE+7FJczH1KspTOAB0ZJwJU7pDZpJukxEPMAmW+/
elhOyJWLA342ig7aR/T4y+XkjUuBtmfwR+Ybh/R4U3l3nrnfhFkE7kXs3lpC4HLphGwuwNPqaoj0
PjCfsekT2vHMHJY5k+INcIg+PGN/sX181KWPXXnm4Rdr9rvD7gh+fvMaLGTk+/DfowNxMNqfHwSj
vtj35915/2A0Hx6K3sHI7/PZrD9g3xSww5pskszl02RZY3MVxT5SjkJfUDJf4SE+plKHN+582wWj
17CAQvwEULulBEgD1WeRG34Uy6uvKbp8W8bSZasmHLQzEi5mYcLVxr7shXzM5LVIIAtykd9wOtTF
h2PxdYlPYWreq92Hyz/++B+L0o1v
===END CRASH DUMP===

**Comment by REALZulfikar** [comment]
Please I need help on this

**Comment by Endermanbugzjfc** [comment]
> Please I need help on this

Why you don't try to find the plugin author lmao

**Comment by REALZulfikar** [comment]
It's by luca28pet

**Comment by REALZulfikar** [comment]
Mod name AdvancedKits

**Comment by REALZulfikar** [comment]
It's fixed
