### ISSUE TITLE
Removing plugin

### ISSUE THREAD

**Issue by iTzDiegoOG** [ScerIO/PocketMine-MP-Android#147]
I don't know how to remove a plugin, so if anyone want to tell me how i can, i thank him

**Comment by kitleyt** [comment]
> Я не знаю, как удалить плагин, поэтому, если кто-то хочет сказать мне, как я могу, я благодарю его

Заходишь в файллвый менеджер находишь папку PocketMine-MP Заходишь в неё заходишь в папку plugins и там добавляешь/удаляешь плагины а папке plugin_data настраиваешь

**Comment by iTzDiegoOG** [comment]
Thank you very much

**Comment by kitleyt** [comment]
> большое спасибо

не за что :)

**Comment by kitleyt** [comment]
Обращайся :) mrbroben56@gmail.com
