### ISSUE TITLE
Кнопка стоп в уведомлениях не работает! 

### ISSUE THREAD

**Issue by kitleyt** [ScerIO/PocketMine-MP-Android#148]
The stop button in notifications doesn't work 
![Screenshot_20200120-234545](https://user-images.githubusercontent.com/53139443/72759674-0c665400-3bdf-11ea-9814-afd9be3d6d19.png)

Nokia 3.2 CPU snapdragon 429 andoid 9.0 PIE, last version on google play

**Comment by SergeShkurko** [comment]
Дубликат #107
