### ISSUE TITLE
Can't join my own server

### ISSUE THREAD

**Issue by MPGaming001** [ScerIO/PocketMine-MP-Android#158]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**ps4 
 - Device: [e.g. Ps4]
 
 - Version [v1.14.20]
.

**Comment by MagesticChicen** [comment]
Anyone know why it ses "throttle automatic restart" 108seconds and then it switches of the server 108seconds after starting I cant even get on my server.

**Comment by MagesticChicen** [comment]
![Screenshot_20200202-131029_PocketMine-MP](https://user-images.githubusercontent.com/60527324/73608633-5aa32c00-45bd-11ea-9d69-174499c1d274.jpg)

**Comment by MagesticChicen** [comment]
Help 😭😭😭

**Comment by SergeShkurko** [comment]
@MagesticChicen https://github.com/ScerIO/PocketMine-MP-Android/issues/128#issuecomment-581162222
