### ISSUE TITLE
Failed to start the server

### ISSUE THREAD

**Issue by Endermanbugzjfc** [ScerIO/PocketMine-MP-Android#162]
**Describe the bug**
An error message pops up and I can't even read the whole message so I don't know how to fix this.

**To Reproduce**
1. Go to 'Server'
2. Click on 'Start' (phar contained

**Expected behavior**
The server starts normally.

**Screenshots**
https://i.imgur.com/Y3fID9I.png

**Smartphone (please complete the following information):**
 - Device: Oneplus A5010 running on Lenovo ideapad 7105 plus
 - OS: Android, Windows
 - Version: 7.1.12, 10

**Additional context**
There are reasons that force me to run pomp on an android device, I just want to say that every pomp for android software are broken in all android emulators :(, hope you guys can find out the problem.

**Comment by SergeShkurko** [comment]
Runed on emulator?

**Comment by Endermanbugzjfc** [comment]
> Runed on emulator?

yea, can u please solve this issue plzzz? I rily need an android pmmp server, and I tried every single emulator or virtual machine and none of them can start the server, only real android devices can and I don't have one, I only have iOS devices :(. Also, some of the companies have the real device server service but are extremely expensive

**Comment by SergeShkurko** [comment]
application does not support computer architecture (x86)

however, you can start the server without an application directly on your computer! without emulator

https://pmmp.readthedocs.io/en/rtfd/installation.html
