### ISSUE TITLE
Friends can't join or they can't see the server

### ISSUE THREAD

**Issue by LerDax** [ScerIO/PocketMine-MP-Android#169]
Info:
So I dont know if this is the problem but:
I taked the address and put Server Ip(or server adress...is the same thing) I used my port and named my server.I did this for my server to be online everytime.Some of them sayd "Unable to connect the world" or idk
Someone sayd she is not seeing it.
Hope you solve it♡.

**Comment by Endermanbugzjfc** [comment]
port forward ur server, youtube search "{ur router company and type} port forwarding"

**Comment by Endermanbugzjfc** [comment]
the scerlo team want solve this
