### ISSUE TITLE
Can't place redstone and command block

### ISSUE THREAD

**Issue by LerDax** [ScerIO/PocketMine-MP-Android#170]
When I place redstone dust(or something that is with redstone like redstone blocks and more....some of them dissapeared like pistons and lanterns) and command block it dissapear.I place it and in 2 seconds it disappears....I tried to accest it in that time of 2 seconds....but I was not able.
Hope this will be solved.(for a plugin creator it need redstone and command blocks to see if it works completely in any situation)

**Comment by Frago9876543210** [comment]
Redstone doesn't implemented on pocketmine. If you need vanilla server you should use bedrock dedicated server.

**Comment by Endermanbugzjfc** [comment]
> When I place redstone dust(or something that is with redstone like redstone blocks and more....some of them dissapeared like pistons and lanterns) and command block it dissapear.I place it and in 2 seconds it disappears....I tried to accest it in that time of 2 seconds....but I was not able.
> Hope this will be solved.(for a plugin creator it need redstone and command blocks to see if it works completely in any situation)

why u need redstone blocks and command blocks for plugins huh

**Comment by Endermanbugzjfc** [comment]
> Redstone doesn't implemented on pocketmine. If you need vanilla server you should use bedrock dedicated server.

poor android ppl don't have software for BeDs rip

**Comment by LerDax** [comment]
So....command block is used for teleportation and things....and if I teleport somewhere maybe it will have errors because on a server needs commands block.Server have a lot of commands that need to be accessed. Hm...I dont think I can explain..but hope you can understand.

**Comment by LerDax** [comment]
Ow....and some blocks dissapeared...like lanterns...
