### ISSUE TITLE
Don't run in pocketmine-mp 3.13.0

### ISSUE THREAD

**Issue by Nunessie** [ScerIO/PocketMine-MP-Android#174]
[ERROR] Selected PHP binary (/data/data/io.scer.pocketmine/php) does not satisfy some requirements.
- PHP >= 7.3.0 is required, but you have PHP 7.2.6.
[ERROR] Please recompile PHP with the needed configuration, or refer to the installation instructions at http://pmmp.rtfd.io/en/rtfd/installation.html.

When i put the pocketmine-mp.phar and try run the server.

**Comment by Endermanbugzjfc** [comment]
Use 3.12 core until they update the bin

**Comment by SergeShkurko** [comment]
Duplicate of #173
