### ISSUE TITLE
IP Changing 

### ISSUE THREAD

**Issue by LittleTheRabbit** [ScerIO/PocketMine-MP-Android#179]
**Describe the bug**
So, today I was playing on my Pocketmine-MP Server, ghen I was disconnected from it. I checked the app, and my IP changed! How do I fix this?

**Expected behavior**
I expected for the IP to stay the same.

**Screenshots**
![Screenshot_20200708-142826_Minecraft](https://user-images.githubusercontent.com/65742175/86958389-172f8980-c12a-11ea-96e0-a794aba1cc3e.jpg)
![Screenshot_20200708-090720_Minecraft](https://user-images.githubusercontent.com/65742175/86958396-1a2a7a00-c12a-11ea-8bb1-e3cdf961791d.jpg)

**Smartphone**
 - Device: Android

**Comment by Frago9876543210** [comment]
Just use port 19132 as default and game will find server automatically
