### ISSUE TITLE
Unable to run php

### ISSUE THREAD

**Issue by ItsbaileyX** [ScerIO/PocketMine-MP-Android#180]
**Describe the bug**
error: errorevent(message=Cannot run program "/data/user/0/io.scer.pocketmine/php
**To Reproduce**
1. Go to 'pocketmine-MP'
2. Click on 'start server'

**Expected behavior**
All of the pocketmine-MP files have been deleted from my phone with just the app there
**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [galaxy A10]
 - OS: [A10]
 - Version [28]

**Additional context**
I just need the files from the android app and paste them in the file

**Comment by Frago9876543210** [comment]
duplicate #177
