### ISSUE TITLE
Error when running server

### ISSUE THREAD

**Issue by swampplays11** [ScerIO/PocketMine-MP-Android#193]
**Describe the bug**
after the last app update with a fresh install the server doesn't start and an error pops up saying:
error:errorEvent(message = cannot run program "/data/user/0/io.scer.pocketmine/php" in directory "/storage/emulated/0/android/data/io.scer.pocketmine/files/pocketmine-mp"): ... (the rest of the error can't be seen due to screen size)
**To Reproduce**

install pocketmine app
let it install pocketmine phar
try to start the server
See error
**Expected behavior**
the server should run as any new pocket mine server.
![Screenshot_20201016-174740_PocketMine-MP](https://user-images.githubusercontent.com/73001480/96311698-15524d80-0fd8-11eb-9f9f-101dc35dac62.jpg)

![Screenshot_20201016-174744_PocketMine-MP](https://user-images.githubusercontent.com/73001480/96311688-0b304f00-0fd8-11eb-93a4-13bdfce1aa33.jpg)
**Smartphone` (please complete the following information):

Device: [Samsung Galaxy A11]
OS: [android]
Version [android 10]
Additional context
i tried giving it all the permissions, tried to clear data and re install but still nothing changed.

**Comment by yukosky** [comment]
Need to update I/O for PHP/Phar to Q/R changes.

**Comment by yukosky** [comment]
![Screenshot_20201018-040436_PocketMine-MP](https://user-images.githubusercontent.com/57292142/96358523-9c4a1780-10f7-11eb-9876-db2fc23a5357.png)
![Screenshot_20201018-040453_Configurações](https://user-images.githubusercontent.com/57292142/96358524-9d7b4480-10f7-11eb-8b4f-559f95ef3802.png)
I don't know the why but, in Android 11 (Custom ROM) is working fine.

**Comment by ILYASSEGAME** [comment]
Is d'ont workin 

![Uploading Screenshot_20201022-200251_PocketMine-MP.jpg…]()

**Comment by yukosky** [comment]
> Is d'ont workin my android device is galaxy a10

?

**Comment by ILYASSEGAME** [comment]
![Uploading Screenshot_20201022-200251_PocketMine-MP.jpg…]()

**Comment by swampplays11** [comment]
> Need to update I/O for PHP/Phar to Q/R changes.

Wdym need to update I/O for PHP/phar to Q/R changes

**Comment by ILYASSEGAME** [comment]
Please give me link to update

🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏


I love realy the app



❤❤❤❤❤❤❤❤❤❤
