### ISSUE TITLE
Can I help with translation

### ISSUE THREAD

**Issue by creeperplayer20** [ScerIO/PocketMine-MP-Android#23]
I can help you with translation in app!

**Comment by Frago9876543210** [comment]
You are welcome: https://github.com/ScerIO/PocketMine-MP-Android/tree/master/app/src/main/res
See values*

**Comment by SergeShkurko** [comment]
@creeperplayer20 you can translate [it file](https://github.com/ScerIO/PocketMine-MP-Android/blob/master/app/src/main/res/values/strings.xml) attach it here

**Comment by creeperplayer20** [comment]
Hi thanks for your reply. You send me email so I can change language to
what I want? 😀🤔

**Comment by SergeShkurko** [comment]
@creeperplayer20 oh, sorry, it file with translate for v1.x.x
for 2.x.x file located here: https://github.com/ScerIO/PocketMine-MP-Android/blob/develop/app/src/main/res/values/strings.xml

github sends an email himself

**Comment by creeperplayer20** [comment]
What language you want? Like espanol, Germany, Russia, and more.....
