### ISSUE TITLE
Translated to Spanish (Latin America)

### ISSUE THREAD

**Issue by bptube** [ScerIO/PocketMine-MP-Android#24]
Hi, here I translated the file into Spanish, I do not know if I miss any other file.
`<resources>
    <string name="app_name" translatable="false">PocketMine-MP</string>
    <string name="server_management">Gestion del servidor</string>
    <string name="start_server">Encender</string>
    <string name="stop_server">Detener</string>
    <string name="downloading">Descargando %name%…</string>
    <string name="error_32bit">Lo siento PocketMine-MP solo admite dispositivos de 64 bits</string>
    <string name="exit">Salir</string>
    <string name="enter">Entrar</string>
    <string name="console">Consola</string>
    <string name="clear">Borrar</string>
    <string name="download_phar">Descargar la última compilación de PocketMine-MP.phar</string>
    <string name="phar_does_not_exist">No se pudo encontrar el archivo PocketMine-MP.phar!</string>
    <string name="kill">Matar servidor</string>
    <string name="not_enough_rights">Para hacer que la aplicación funcione correctamente, ¡debe otorgar acceso a la memoria de tu dispositivo!</string>
    <string name="join_beta">Puedes unirte a la beta <b>v2.0.0!</b> en\n\n 	https://play.google.com/apps/testing/io.scer.pocketmine</string>
</resources>`

**Comment by bptube** [comment]
https://pastebin.com/EXr9asyF

**Comment by SergeShkurko** [comment]
@bptube oh, sorry, it file with text for v1.x.x
for 2.x.x file located here: https://github.com/ScerIO/PocketMine-MP-Android/blob/develop/app/src/main/res/values/strings.xml

**Comment by SergeShkurko** [comment]
resolved in #29
