### ISSUE TITLE
Crash/lag issues.

### ISSUE THREAD

**Issue by DANRULEZ123** [ScerIO/PocketMine-MP-Android#26]
**Describe the bug**

**To Reproduce**

**Expected behavior**
I expect it to be lag and crash free.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Alectel]
 - OS: [e.g. Android 7.0]

**Additional context**
So basically my app keeps crashing and lagging horriblely.

**Comment by SergeShkurko** [comment]
@DANRULEZ123 Can you describe the problem in more detail?
