### ISSUE TITLE
Repeatly asking permission

### ISSUE THREAD

**Issue by Guardian56** [ScerIO/PocketMine-MP-Android#3]
I install this app on my phone i5K ADVAN (Android 6.0), but thats not happen on Android 7.0. So the bug is when i open the app its asking storage permission. Its always happen everytime i open the app

**Comment by SergeShkurko** [comment]
@Guardian56 As I understand after the application has issued permissions to read from memory, the application closes and does not open any more, right?

**Comment by SergeShkurko** [comment]
And what about the version of android, did not understand what version

**Comment by SergeShkurko** [comment]
@Guardian56 you can accept invite to join beta releases (https://play.google.com/apps/testing/io.scer.pocketmine) and check again

**Comment by SergeShkurko** [comment]
Write here, mentioning my name if the problem persists.
