### ISSUE TITLE
Invis. Plugin

### ISSUE THREAD

**Issue by jruffy** [ScerIO/PocketMine-MP-Android#36]
I copied devtools to the plugins folder but whenever I started the server it can't be seen by the server,the devtools version is 1.13.3 but I rewrite the API version by converting the .phar to .zip using the website phar.scer.io then reversing it from .zip to .phar then putting it back to the plugin folder then the server cannot see if it even exists but in the unrewrited devtools it can be seen but got old api...btw I'm not sure if it's with the Pocketmine or the plugin itself...but I hope it will be fixed soon or get a guide on how to fix it,thanks!

Device:Lenovo K6 Note
OS:Android 7.0
![Screenshot_20190522-073641](https://user-images.githubusercontent.com/22023587/58137330-78fe0d00-7c64-11e9-981b-416cfbd1f13e.jpeg)
![Screenshot_20190522-073628](https://user-images.githubusercontent.com/22023587/58137338-7c919400-7c64-11e9-9d2b-3c66152d1bed.jpeg)

**Comment by Frago9876543210** [comment]
Please download it from poggit.pmmp.io

**Comment by jruffy** [comment]
Thanks,but I got it from there...
