### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by ChampOfGamesYT** [ScerIO/PocketMine-MP-Android#37]
Hello, I want to add german for you.

**Comment by Limon253648936** [comment]
Add russian language

**Comment by SergeShkurko** [comment]
> Add russian language

вообще-то он уже есть

**Comment by SergeShkurko** [comment]
@ChampOfGamesYT you can copy and translate it file: https://github.com/ScerIO/PocketMine-MP-Android/blob/master/app/src/main/res/values/strings.xml
