### ISSUE TITLE
Должна быть страница плагинов, где вы можете скачать плагины mcpe, такие как старый карманный компьютер, и вы должны создать дискорд-сервер для более легкой поддержки и обратной связи.

### ISSUE THREAD

**Issue by GreatZardasht** [ScerIO/PocketMine-MP-Android#38]
Должна быть страница плагинов, где вы можете скачать плагины mcpe, такие как старый карманный компьютер, и вы должны создать дискорд-сервер для более легкой поддержки и обратной связи.

**Comment by Limon253648936** [comment]
Хорошо я это все сделал но что дальше?

**Comment by SergeShkurko** [comment]
Dublicate of #34
