### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by BlazingOne** [ScerIO/PocketMine-MP-Android#4]
Ok sorry for that issue, that was kinda dumb, anyway with the new BETA it no longer crashes, but it provides this error, sorry for wasting your time is this.. time wasting.

https://i.gyazo.com/969fa4fde4ce239ab4c3aa0c6a97be9c.png

**Comment by SergeShkurko** [comment]
@BlazingOne try remove folder `PocketMine-MP` from storage and restart app

**Comment by BlazingOne** [comment]
Same issue..

**Comment by Frago9876543210** [comment]
Are you trying to do this on a sdcard?

**Comment by Frago9876543210** [comment]
Try create server.log in PM folder by hands

**Comment by BlazingOne** [comment]
Sorry bout that, went away from my phone for some time, how exactly will I create that

**Comment by BlazingOne** [comment]
Nothing inside the server.log folder and still crashes

**Comment by SergeShkurko** [comment]
Write here, mentioning my name if the problem persists.
