### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Alfree101** [ScerIO/PocketMine-MP-Android#40]
When my friend joined the server that i just started, my friend destroy a block and left the server and got the message "Internal Server Error" but its for my friend.

1. Go to Play
2. Join server
3. Break a block

My friend's phone
 - Device: Samsung
 - Version: 6.0.1

This is a beta version of the app

**Comment by Profee828** [comment]
Plugin Error.

**Comment by Profee828** [comment]
Can You Give Me FTP?

**Comment by Frago9876543210** [comment]
report it to https://github.com/pmmp/PocketMine-MP please
