### ISSUE TITLE
Auto Disconnect

### ISSUE THREAD

**Issue by lixorhaxz** [ScerIO/PocketMine-MP-Android#51]
Hi Team PocketMine-MP.
my name is Lixor
so, why i always disconnected from game and the logs say : (name) Time Out 
all my friend disconnected at same time
I dont know that a bug or what?
please reply
Thank You
~ LixorHaxz
Device: Xiaomi Redmi 4x
Ram: 4GB
Internal: 64GB
![Screenshot_2019-06-25-13-59-27-106_io scer pocketmine](https://user-images.githubusercontent.com/47329758/60072903-83269600-9751-11e9-973e-c0a65efff474.png)

**Comment by yoraze** [comment]
PMMP bug lol...

**Comment by yoraze** [comment]
And to be more precise - pmmp feature. This is not a bug app!

**Comment by SergeShkurko** [comment]
that way https://forums.pmmp.io/
