### ISSUE TITLE
32Bit

### ISSUE THREAD

**Issue by Minexst** [ScerIO/PocketMine-MP-Android#54]
Hello, I am running PocketMine server until my Host shutdown. Tried to edit the app with APK editor but couldn't remove that only 64bit page please make it. Or just send me a 32 bit to stop my Network from dying I also tried other apps  but they don't work I need you're help please!

**Comment by Frago9876543210** [comment]
Official pmmp/PocketMine-MP dropped 32 bit support since 2017

**Comment by Frago9876543210** [comment]
This is not application problem
