### ISSUE TITLE
The IP issue

### ISSUE THREAD

**Issue by MinecraftShadow098** [ScerIO/PocketMine-MP-Android#56]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MinecraftShadow098** [comment]
Everytime i restart my server a new ip come out and thats really annoying pls stop it.

**Comment by dearminder** [comment]
It is your device problem. Server is being hosted propably on ip of your device. If you have set dynamic ip adress then the ip is propably changing after every wifi disable (depending on all other devices in your network)
