### ISSUE TITLE
Locating Server forever!

### ISSUE THREAD

**Issue by Iust1n** [ScerIO/PocketMine-MP-Android#57]
I have a problem and idk why i have it. sometimes i grt randomly kicked from my server. what can i do?

**Comment by yoraze** [comment]
Close this issue pls, this is a PMMP bug, not app bug.

**Comment by Iust1n** [comment]
Ok thx

Dum, 21 iul. 2019, 9:06 p.m. Ivan <notifications@github.com> a scris:

**Comment by BXXD101** [comment]
This is because pocketmine mp doesnt support ipv6 yet. Disable it on your router and try again
