### ISSUE TITLE
my friends can not enter the server

### ISSUE THREAD

**Issue by MufinaYT** [ScerIO/PocketMine-MP-Android#58]
![Screenshot_20190715-155839_Minecraft](https://user-images.githubusercontent.com/52923404/61221776-77f3d400-a719-11e9-9541-fb304b1e04cc.jpg)
![received_2119273808373576](https://user-images.githubusercontent.com/52923404/61221804-880bb380-a719-11e9-827e-78511946164a.png)

Pls help i have server on pocketmine and i have 50 slots :( idk why my friends talk to me there is no server when I go into minecraft everything is plsss help

**Comment by dearminder** [comment]
You have to Port Forward

**Comment by G0DSISPRO** [comment]
How do i port forward?

**Comment by G0DSISPRO** [comment]
> You have to Port Forward

How do i do that? I use pldt

**Comment by G0DSISPRO** [comment]
> GOOGLE IT (how to portforward )

Ok
