### ISSUE TITLE
[RakLibServer thread/NOTICE]: Blocked {ip} for 300 seconds

### ISSUE THREAD

**Issue by SuperByteStudio** [ScerIO/PocketMine-MP-Android#59]
I get kicked from my server

I start the server, i join to the server, i get kicked

**Expected behavior**
I join to my server and i dont get kiced

**Smartphone (please complete the following information):**
 - Device: P20 Lite

**Comment by yoraze** [comment]
Close this issue pls, this is a PMMP "bug"(not bug), not app bug.
