### ISSUE TITLE
Could you share the way to build the PHP-Executable staticly,please?

### ISSUE THREAD

**Issue by YxMingY** [ScerIO/PocketMine-MP-Android#6]
Could you share the way to build the PHP-Executable staticly,please?
I am so stupid that I always build it failed,though I try my best to do it...
I really truly specially want to know that how to do it.
If you like, just teach me or us please!!!
Even I can provide you with some money, as long as you share the way please!
A sincere request.
Best wishes for you.
Thanks.

**Comment by Frago9876543210** [comment]
https://github.com/pmmp/php-build-scripts/blob/master/README.md just build gcc for arch64 and compile php

**Comment by SergeShkurko** [comment]
@YxMingY you can use [it script](https://github.com/ScerIO/php-build)

**Comment by YxMingY** [comment]
> https://github.com/pmmp/php-build-scripts/blob/master/README.md just build gcc for arch64 and compile php

Oh, but I haven't built by it successfully.

**Comment by YxMingY** [comment]
> @YxMingY you can use [it script](https://github.com/ScerIO/php-build)

Thanks, I will have a try.
