### ISSUE TITLE
[BETA] Crash after Server start

### ISSUE THREAD

**Issue by dearminder** [ScerIO/PocketMine-MP-Android#7]
after Starting server app immediately crashes (tried clearing pocketmine folder)

**Comment by Frago9876543210** [comment]
Show logs

**Comment by dearminder** [comment]
No logs. App crashes not server inside app

**Comment by SergeShkurko** [comment]
@dearminder, try clear app data and restart. If app again crashes please write your device specifications

**Comment by dearminder** [comment]
Still crashing.
Xiaomi Mi 5 3/32gb
Android 9.0.0

**Comment by SergeShkurko** [comment]
@dearminder try new version `2.0.0-beta2`
It is new permission in android 9 (see [foreground services change in new api ](https://developer.android.com/about/versions/pie/android-9.0-changes-28))

**Comment by SergeShkurko** [comment]
@dearminder any news?

**Comment by dearminder** [comment]
oh sorry i forgot to mention that its fixed :)

**Comment by MarcusDDS1609** [comment]
how did you fix it?

**Comment by dearminder** [comment]
> 
> 
> how did you fix it?

This bug is old and got fixed in beta and also in release
