### ISSUE TITLE
Port Forwarding

### ISSUE THREAD

**Issue by WierdBtothers** [ScerIO/PocketMine-MP-Android#70]
Well this isn't really a bug, but I've port forward my server making my LAN into public, now the problem is that I don't know what's the server IP, I am not sure if its my local IP because I tried checking if it was with an online website, it told me that my local IP can't be the server's IP, so I moved on to my Public IP, but it couldn't find my server even tho I turned it on, I am getting really confused and I hope someone could help me out.

Mobile Device - Samsung Galaxy S6

**Comment by BXXD101** [comment]
Make sure you forwarded to right local ip adress

**Comment by WierdBtothers** [comment]
BXXD101 I portforwarded it on local IP, does that make my Local IP the main IP for my server?

**Comment by BXXD101** [comment]
No. The wich u have to give others is the public ip. But first make sure that youre giving the correct public ip

**Comment by WierdBtothers** [comment]
May you suggest any sites to give me my public IP? It doesn't allow anyone to connect.

**Comment by ZappyMC** [comment]
Yeah I'm having the same issue my friends can't join the server even tho I port forwarded it someone please help

**Comment by SergeShkurko** [comment]
Clone of #58

**Comment by ZappyMC** [comment]
Why was this closed if the issue was not resolved how do other players join the server I tried to portforward but it doesn't pop up for other people

**Comment by WierdBtothers** [comment]
Wtf I didn't solve my problem, support is trash I can't even start a server thanks so much 'support' team...
