### ISSUE TITLE
Pocketmine-MP Update for MCPE 1.13

### ISSUE THREAD

**Issue by EitanKai** [ScerIO/PocketMine-MP-Android#71]
**Is your feature request related to a problem? Please describe.**
I just want a request for Pocketmine-MP to be updated that will be compatible for MCPE 1.13 (Beta). Because, there is a problem with MCPE 1.12 which is..., when someone will join on my server, it says "unable to connect to world".

**Describe the solution you'd like**
The only solution to this kind of problem, is to update Pocketmine-MP that will support MCPE 1.13 (beta).

**Describe alternatives you've considered**
Also, let us change the ip of our server.

**Additional context**
In additional, I want the plugins to be updated too. That's all! I hope you'll consider this request. Thanks in advance!

**Comment by Frago9876543210** [comment]
This it a __pocketmine launcher__, not pocketmine core
