### ISSUE TITLE
How i can fix that

### ISSUE THREAD

**Issue by Iust1n** [ScerIO/PocketMine-MP-Android#77]
i dont know what that means but i want to know what is it and how i can fix
![Screenshot_2019-08-03-23-02-59](https://user-images.githubusercontent.com/52248587/62416423-46e53000-b643-11e9-9f4d-24eddb259d7f.png)
![Screenshot_2019-08-03-23-02-46](https://user-images.githubusercontent.com/52248587/62416425-4d73a780-b643-11e9-9f7a-69153be13d07.png)
![Screenshot_2019-08-03-23-02-59](https://user-images.githubusercontent.com/52248587/62416427-55334c00-b643-11e9-8243-8d577fa96a88.png)

**Comment by SergeShkurko** [comment]
it has no connection with application development. you're about
