### ISSUE TITLE
Players cant join with me server

### ISSUE THREAD

**Issue by aihexpvp** [ScerIO/PocketMine-MP-Android#82]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by eforce67** [comment]
Did you not portfoward

**Comment by G0DSISPRO** [comment]
Teach me how to port forward cause im usingpldt

**Comment by eforce67** [comment]
Watch a tutorial

**Comment by G0DSISPRO** [comment]
Ik that but im using pldtfiber

**Comment by MeRainbowPanda** [comment]
here is a link to a port forwarding totourial 
https://youtu.be/-4_tMgyVO6g
