### ISSUE TITLE
Добавьте возможность импортировать уже созданные игроком миры

### ISSUE THREAD

**Issue by Krackeen777** [ScerIO/PocketMine-MP-Android#86]
Мне кажется, что использование уже созданных игроком миров для серверов могло бы увеличить оценку и популярность приложения!
К примеру, я всегда мечтал о своем сервере, и я даже сделал карту для него, но, к сожалению, я не могу импортировать свой мир с несколькими нас. пунктами для своего сервера...

**Comment by Frago9876543210** [comment]
Мы не делаем серверное ПО, а делаем лаунчер PM для андроида. Что касается импорта миров из одиночный игры, то PMMP 4.0 умеет читать карты формата leveldb, а anvil там больше не поддерживается
