### ISSUE TITLE
Plugin does not work on Android version but it works perfectly on Windows version

### ISSUE THREAD

**Issue by MisledPaul58** [ScerIO/PocketMine-MP-Android#87]
First,sorry of my english, im spanish...
This error happens with this plugin: https://poggit.pmmp.io/ci/larryTheCoder/SkyWarsForPE/SkyWarsForPE when I type a command of the plugin like /sw help,it says this https://drive.google.com/file/d/1-8NyNKX20YLDgI4c2xYSJxjLD2NvVto6/view?usp=drivesdk
My device is a tablet samsung galaxy tab A6 SM-T580 with android oreo(8.1.0)
I tested it with only that plugin and it happen the same thing.
Please help.

**Comment by SergeShkurko** [comment]
Most likely the problem is with the plugin itself
