### ISSUE TITLE
I'm just some blocks are missing from the world

### ISSUE THREAD

**Issue by bob12345678901234555** [ScerIO/PocketMine-MP-Android#98]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Flame4DX** [comment]
Some Blocks and items including cod,salmon and dolphin are missing in the server

**Comment by Flame4DX** [comment]
Some of the blocks and items including mob are not in the server

The missing blocks,mob and items:
-Loom,Smiting Table,Blast Furness, Smoker,Grind Stone,Map,Located Map,Kelp(including in the ocean),Sea grass(including in the ocean,river and swapm),All coral block,Etc.

**Comment by bob12345678901234555** [comment]
Yes and I would love it if you would add them in please

**Comment by Frago9876543210** [comment]
this is just launcher for pocketmine, NOT software support hotline

**Comment by bob12345678901234555** [comment]
Hey! ✌️ Download a new cool game Bowmasters! 😂 It's hilarious!!! 😂😂
Download Bowmasters FOR FREE right now! 🔥🔥🔥😍👉
http://play.google.com/store/apps/details?id=com.miniclip.bowmasters
