### ISSUE TITLE
The servers are down rn and wont make a server if you get it to even start

### ISSUE THREAD

**Issue by retroNexu** [ScerIO/PocketMine-MP-Android#99]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by NizarJR4** [comment]
Sat_Sep_21-07.05.14-UTC_2019.log"

**Comment by SergeShkurko** [comment]
insufficient description
